name: Playwright Tests
on: 
  workflow_dispatch:
    inputs:
      suite:
        description: 'Test suite'
        required: true
        default: 'warning'
        type: choice
        options:
          - bstackdemo
          - bstackdemo50
          - bstackdemo100
      project:
        description: 'Chrome, Chromium'
        required: true
        default: 'warning'
        type: choice
        options:
          - chromium
          - chrome

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Playwright
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        run: sudo apt install nodejs
      - name: Setup NPM
        run: sudo apt install npm
      - name: Versions
        run: node -v && npm -v
      - name: npm-install
        run: npm install
      - name: Post LS
        run: ls
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test tests/${{ inputs.suite }} --project ${{ inputs.project }}